### ISSUE TITLE
OWA on Yosemite

### ISSUE THREAD

**Issue by GiorgosSant** [padams/Open-Web-Analytics#148]
I have installed owa on OS/X Yosemite, php 5.5.29. 
I have set up a profile for a website on the same server. Unfortunately, I do not get any statistics for the site at all. 
I have copied the php code to my webpages from the link "Get Tracking Code"... 
I get the following message on the owa page:
Strict standards: Non-static method owa_sanitize::cleanInput() should not be called statically in /Library/WebServer/Documents/owa/modules/base/classes/sanitize.php on line 329
and the following warnings on the website:
( ! ) Warning: fsockopen(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Library/WebServer/Documents/owa/includes/Snoopy.class.php on line 1142
( ! ) Warning: fsockopen(): unable to connect to api.hostip.info:80 (php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known) in /Library/WebServer/Documents/owa/includes/Snoopy.class.php on line 1142

Any help is appreciated :)
Thank you in advance!

**Comment by padams** [comment]
Can you give the code in master a try I believe this is fixed there.

**Comment by dac2020** [comment]
We are running 1.5.8 on a wordpress site and still seeing this error in the logs. 

PHP Warning:  fsockopen(): unable to connect to api.hostip.info:80 
(php_network_getaddresses: getaddrinfo failed: Name or service not known) in /var/www/html/wp-content/plugins/owa/includes/Snoopy.class.php on line 1142, 
referer: http://www.mydomain.com/wp-admin/post.php?post=3034&action=edit

**Comment by padams** [comment]
1.5.9 removes hostip as a geolocation provider as they seem to no longer be operating their API.

**Comment by dac2020** [comment]
Upgrading.
