### ISSUE TITLE
Page view counts with URLs containing ampersands are always stated to be 0 on "page detail:"

### ISSUE THREAD

**Issue by buggbear** [padams/Open-Web-Analytics#316]
"Page view" counts with URLs containing ampersands are always stated to be 0 on "page detail", alltough the number of page views are correctly counted on "Content Overview", "Top Pages".

The sql query for page view is not properly generated. When I change all &amp;amp; to the & symbol only, the query returns the correct values (table of views per each day).

Example of a non working query, taken from debug log.

Query: SELECT COUNT(DISTINCT request.session_id) as visits, COUNT(request.id) as pageViews FROM owa_request as request
JOIN owa_document AS document_via_document_id ON request.document_id = document_via_document_id.id WHERE request.yyyymmdd BETWEEN '20180218' AND '20180225' A
ND document_via_document_id.url = 'http://www.-------.com/index.php?option=com_virtuemart&amp;amp;view=productdetails&amp;amp;virtuemart_product_id=5&
amp;amp;virtuemart_category_id=123&amp;amp;Itemid=1242&amp;amp;lang=de' AND request.site_id = '963cccfd012db7ceafdc48e8e6d931ad'    LIMIT 1

Revision: 1750, current TRUNK

**Comment by padams** [comment]
I believe this is fixed in master. could you test with that code and see if it fixes this issue?

**Comment by PauloBoaventura** [comment]
Hello, I installed OWA and after 3 days in our ... In the data ...
I'm using Joomla.

Should I have any permissions on the .htaccess or something similar?

Can I use Magento?

How to proceed?

Thank you for the development and I really want to print whatever you need ...

Att,
Paulo


BR
olá instalei o OWA e apos 3 dias nenhuma mudança nos dados...
Estou usando no Joomla.

Deve ter alguma permissão no .htaccess ou algo similar?

Posso usar em Magento?

Como proceder?

Agradeço pelo desenvolvimento e quero muito utilizar para reportar qualquer melhoria necessaria...

Att,
Paulo

**Comment by buggbear** [comment]
Thanks for you fast response, Peter! 

I switched to 1.6.1 from MASTER branch, cleared cache but get the same problem. The query it generates still shows those extra amp; in the log file

like:
virtuemart_product_id=2&amp;amp;virtuemart_category_id=13&amp;amp;

**Comment by PauloBoaventura** [comment]
Hi, @buggbear 
I use Joomla and see you too.
I have no answer at all.
Can you tell me if I have to do any specific configuration?


Hi, @padams 
I'm attaching my log. To take a look and see what I can modify.
Thanks in advance!

[errors_5ee59642f92ee9e4a1f8df137f480ed1.txt](https://github.com/padams/Open-Web-Analytics/files/1759860/errors_5ee59642f92ee9e4a1f8df137f480ed1.txt)

**Comment by buggbear** [comment]
Paulo,

Please open your own issue. Click the "NEW ISSUE" button in the upper left corner and describe your problem.

This is not a chat, it's a bug tracker. 

Best regards.

**Comment by buggbear** [comment]
Now, after logging visitors for a while with master 1.6.1, it seems all pages that to not contain concatenated  url parameters (like &param=value) do work completly fine.

All those pages that contain a longer list of parameters separated with & are NOT COUNTED on the "Page view". There I always get 0 (due to the incorrect SELECT string mentioned in the first report).

**Comment by padams** [comment]
@Maaiins looks like this is another sanitization issue. This time it's with respect to the resultSet API requests that contain URLs as params.

**Comment by padams** [comment]
I think the issue here is owa_resultSetManager::constraintsStringToArray and double encoding.

**Comment by padams** [comment]
I added a quick fix but it might be too aggressive in allowing HTML to sneak through in API requests. @Maaiins can you take a look and think about ways to tighten this up?

**Comment by padams** [comment]
I actually think this ia generalized issue with html encoding of all API request params. It really only manifests itself when a URL is used as a param.

**Comment by padams** [comment]
More investigation. All OWA request params are currently running through `owa_sanitize::escapeForDisplay` you can see this happen in `owa_requestContainer` class. This is the safest way to handle input attacks but it then means that we need downstream code to handle the fall out. We may need to enumerate API params so that we can add type checking logic (like we do in base/module.php for tracking params).

It's harder though because the value of certain API request params is a concatenated string full of other params. For example:

?constrains=pagePath==http://www.foo.com?param1=bar&params2=zed

**Comment by padams** [comment]
OK I'm starting to think that `owa_sanitize::escapeForDisplay` is a bad idea. we may need another sanitize method that strips HTML but doesn't encode HTML entities.

**Comment by Maaiins** [comment]
The fix is quite easy in my opinion, use `htmlspecialchars_decode()` instead of `html_entity_decode()`.
`htmlspecialchars_decode()` converts only special chars and no html.

https://www.php.net/manual/de/function.htmlspecialchars-decode.php

**Comment by padams** [comment]
Ok. I think the solution is even simpler...

 The global input sanitization that was happening in `owa_requestContainer` was unnecessarily encoding HTML entities even though the code was striping all HTML tags from input right before that. 

Encoding of HTML entities should really only be done as part of output to templates which is why it's present in the `owa_sanitize::escapeForDisplay`.

The bug was that i didn't realize that encoding HTML flag is set to true in the default options for `owa_sanitize::cleanInput`. Because of that it needs to be explicitly turned off which the commit i pushed just did.

Please test and reopen if you see any more weirdness.
