### ISSUE TITLE
"Do-Not-Track" Browser Settings

### ISSUE THREAD

**Issue by znrR** [padams/Open-Web-Analytics#448]
Hi Peter, although I learned  that DNT is somewhat depreciated around the web (sadly) I have a question in regards to https://github.com/padams/Open-Web-Analytics/issues/336#issuecomment-394234221

I set FX to "do-not-track"  and tested on https://allaboutdnt.com/ and the site shows "Your browser is sending a DNT signal."  But when visiting our site with OWA implemented the browser still gets tracked. To me it reads in your post like if the browser is sending the signal, OWA should not track - or do I need to additionally implement the "Pause  / Unpause" Cmnd  as described in  https://github.com/padams/Open-Web-Analytics/issues/338 to make DNT work?

thanks and best from berlin!

**Comment by padams** [comment]
Which browser/os/version are you using?

**Comment by znrR** [comment]
Firefox 72.0.1 on MacOS 10.15.1

**Comment by padams** [comment]
Seems like we are incorrectly checking the return value of the doNotTrack property. Should be a check for === '1' and not === 'yes'.

**Comment by padams** [comment]
Fixed.

**Comment by znrR** [comment]
Hi peter, i am afraid its still not working for me.. how can i help you debug? Browser is eg: FX or Chrome

**Comment by Maaiins** [comment]
Im using chrome and dnt is respected correctly, when i use javascript tracking. I think the PHP tracker is not respecting any dnt parameters.

**Comment by padams** [comment]
@znrR are you using the PHP tracker?

**Comment by znrR** [comment]
using the WP version, and hence the automagically inserted jscript! just tested DNT again in FX and it works as expected, my bad - sry...
